name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.13' }
      - run: pip install -r requirements.txt
      - name: Preflight
        run: python tools/preflight_check.py
      - name: Golden tests
        run: python tests/golden/run_golden_tests.py
      - name: Sample export (md+html)
        run: |
          python run_kai.py --domain finsetreport --input "온보딩 최적화 전략(자동체크)" --export all
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kai-output
          path: output/**/*
