name: Golden Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  golden:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Preflight
        run: python tools/preflight_check.py
      - name: Golden (deterministic)
        env:
          KAI_DETERMINISTIC: "1"
        run: python tests/golden/run_golden_tests.py --deterministic